[versions]
compose-ui-version = "1.3.1"
androidx-core-version = "1.9.0"
androidx-lifecycle-version = "2.3.1"
activity-compose-version = "1.3.1"
koin = "3.3.1"
koin-compose = "3.3.0"
coil-compose = "2.2.2"
play-services-location = "20.0.0"
locus-android = "4.1.0"
retrofit = "2.9.0"
retrofit2-kotlinx-serialization-converter = "0.8.0"
kotlinx-serialization = "1.4.1"
okhttp-logging-interceptor = "4.10.0"
androidx-work = "2.7.1"
easypermissions-ktx = "1.0.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-version" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-version" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose-version" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui-version" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-ui-version" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui-version" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui-version" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }
gms-play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
locus-android = { module = "com.github.BirjuVachhani:locus-android", version.ref = "locus-android" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-kotlinx-serialization-converter" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging-interceptor" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
easypermissions-ktx = { module = "com.vmadalin:easypermissions-ktx", version.ref = "easypermissions-ktx" }

[bundles]
composeUi = ["compose-material", "compose-tooling-preview", "activity-compose", "coil-compose"]
composeDebug = ["compose-tooling", "compose-test-manifest"]
koin = ["koin-android", "koin-androidx-compose"]
androidLocation = ["gms-play-services-location", "locus-android"]
retrofit = ["retrofit", "retrofit2-kotlinx-serialization-converter", "okhttp-logging-interceptor"]

[plugins]
gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.0.0" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "1.6.10" }
